---
title: "Halcones de Costa Rica"
author: "Rosario Ureña Mena"
format: html
html:
page-layout: custom
server: shiny
---
```{r}
#| context: server
```

```{r}
#| warning: false
#| message: false
#| code-fold: true
#| echo: fenced
library(shiny)
library(rsconnect)
library(tidyverse)
library(ggplot2)
library(readr)
library(plotly)
library(DT)
library(dplyr)


rsconnect::setAccountInfo(name='1b6bd6-rosurme',
			  token='DDAB307F46C05C33C788C385374211F9',
			  secret='sPLJaQO5rP04NbXvQCQExgz1Q1XvPNIvDb0H7VA9')
getwd()

deployApp()
                     
```

```{r}
#| label: importacion-de-datos-de-halcones
#| warning: false
#| message: false
#| code-fold: true

halcones <- read_delim(file= "C:/Users/rosur/OneDrive/Documentos/MAESTRIA GIRH/CURSO PROGRAMACIÓN/TRABAJO FINAL/Datos/Halcon.csv",
                       col_select = c(
      "species",
      "stateProvince",
      "locality",
      "eventDate",
      "decimalLongitude",
      "decimalLatitude"),
      locale = locale(encoding = "UTF-8")  )
```

